# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-01 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='item_type',
            field=models.CharField(choices=[('txt', 'Text')], default='txt', max_length=3),
        ),
    ]
