# Generated by Django 2.2.14 on 2020-09-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lrex_study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Give the materials a name.', max_length=100)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('item_list_distribution', models.CharField(choices=[('latin-square', 'Latin-Square Distribution'), ('all-to-all', 'Show all conditions to all participants')], default='latin-square', help_text='How to distribute items across lists.', max_length=16)),
                ('is_filler', models.BooleanField(default=False, help_text='Mark the items of this materials as fillers. This setting will be relevant if you choose to pseudo-randomize the questionnaire.')),
                ('is_example', models.BooleanField(default=False, help_text='Items will all be in block 0 (preceding items from all other materials).')),
                ('block', models.IntegerField(default=-1, help_text='Items will all be in this block (-1 = no automatic block assignment).')),
                ('items_validated', models.BooleanField(default=False)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='lrex_study.Study')),
            ],
            options={
                'ordering': ['study', 'title'],
            },
        ),
    ]
