# Generated by Django 2.2.11 on 2020-05-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='subject_id',
            new_name='participant_id',
        ),
    ]
