# Generated by Django 2.0.1 on 2018-04-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='id',
            field=models.CharField(blank=True, help_text='TODO', max_length=200, null=True),
        ),
    ]
