# Generated by Django 2.2.14 on 2020-11-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('trial', 'questionnaire_item', 'question')},
        ),
    ]
