# Generated by Django 2.1.1 on 2018-10-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireblock',
            name='randomization',
            field=models.CharField(choices=[('none', 'Keep item order'), ('true', 'Randomize'), ('pseudo', 'Pseudo-randomize')], default='true', help_text='Randomize items in each questionnaire block', max_length=8),
        ),
    ]
