# Generated by Django 2.0.1 on 2018-03-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrial',
            name='participant',
        ),
        migrations.AddField(
            model_name='usertrial',
            name='id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
