# Generated by Django 2.2.5 on 2019-11-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='rating_proof',
        ),
    ]
