# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertrialitem',
            old_name='usertrial',
            new_name='user_trial',
        ),
    ]
