# Generated by Django 2.0.5 on 2018-06-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0002_auto_20180530_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='rating_proof',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
