# Generated by Django 2.2.14 on 2020-11-13 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0002_auto_20201113_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='trial',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
