# Generated by Django 2.0.1 on 2018-03-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0002_auto_20180316_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertrial',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterModelOptions(
            name='usertrialitem',
            options={'ordering': ['number']},
        ),
    ]
