# Generated by Django 2.1.1 on 2018-10-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0002_pseudo_randomization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireblock',
            name='randomization',
            field=models.CharField(choices=[('pseudo', 'Pseudo-randomize'), ('none', 'Keep item order'), ('true', 'Randomize')], default='pseudo', help_text='Randomize items in each questionnaire block', max_length=8),
        ),
    ]
