# Generated by Django 2.2.14 on 2021-02-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0003_auto_20201113_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireblock',
            name='randomization',
            field=models.CharField(choices=[('pseudo', 'Pseudo-randomize'), ('true', 'Randomize'), ('none', 'Keep item order')], default='pseudo', help_text='Randomize items in each questionnaire block.', max_length=8),
        ),
    ]
