# Generated by Django 2.2.7 on 2019-12-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0003_auto_20191205_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
