# Generated by Django 2.2.7 on 2020-02-02 14:14

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0004_trial_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireblock',
            name='short_instructions',
            field=markdownx.models.MarkdownxField(blank=True, help_text='You can optionally provide a shorter version of the block instructions that the participant can access again during participation as a reminder of the task.', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireblock',
            name='instructions',
            field=markdownx.models.MarkdownxField(blank=True, help_text='These instructions will be presented to the participant before the questionnaire block begins.', max_length=5000, null=True),
        ),
    ]
