# Generated by Django 2.2.7 on 2020-02-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0005_auto_20200202_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicvalue',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='lrex_trial.Trial'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='lrex_study.Study'),
        ),
        migrations.AlterField(
            model_name='questionnaireblock',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_blocks', to='lrex_study.Study'),
        ),
        migrations.AlterField(
            model_name='questionnaireitem',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_items', to='lrex_trial.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionproperty',
            name='questionnaire_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_properties', to='lrex_trial.QuestionnaireItem'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='questionnaire_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='lrex_trial.QuestionnaireItem'),
        ),
    ]
