# Generated by Django 2.1.3 on 2018-11-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0008_questionnaire_slug_3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ['number']},
        ),
    ]
