# Generated by Django 2.1.3 on 2018-11-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0009_questionnaire_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='subject_id',
            field=models.CharField(blank=True, help_text='Provide an identification number/name (as instructed by the experimenter).', max_length=200, null=True, verbose_name='ID'),
        ),
    ]
