# Generated by Django 2.1.3 on 2018-11-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0011_trial_subject_id_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='id',
        ),
    ]
