# Generated by Django 2.1.4 on 2019-01-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0012_remove_trial_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['pk']},
        ),
    ]
