# Generated by Django 2.1.7 on 2019-03-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0013_rating_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='slug',
            field=models.SlugField(max_length=110, unique=True),
        ),
    ]
