# Generated by Django 2.1.7 on 2019-03-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0014_slug_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['trial', 'questionnaire_item', 'question']},
        ),
        migrations.AddField(
            model_name='rating',
            name='question',
            field=models.IntegerField(default=0),
        ),
    ]
