# Generated by Django 2.1.1 on 2018-09-24 07:35

from django.db import migrations


def update(apps, schema_editor):
    Trial = apps.get_model('lrex_trial', 'Trial')
    QuestionnaireItem = apps.get_model('lrex_trial', 'QuestionnaireItem')
    for trial  in Trial.objects.all():
        questionnaire_items = QuestionnaireItem.objects.all().filter(questionnaire__trial=trial)
        for questionnare_item in questionnaire_items:
            ratings = questionnare_item.rating_set.all().filter(trial=trial).order_by('pk')
            for i, rating in enumerate(ratings):
                rating.question = i
                rating.save(update_fields=['question'])


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0015_ordering'),
    ]

    operations = [
        migrations.RunPython(update, reverse_code=migrations.RunPython.noop),
    ]
