# Generated by Django 2.1.1 on 2018-09-24 07:35
from datetime import timedelta

from django.db import migrations
from django.utils.timezone import now


def update(apps, schema_editor):
    QuestionnaireItem = apps.get_model('lrex_trial', 'QuestionnaireItem')
    for questionnare_item  in QuestionnaireItem.objects.all():
        ratings = questionnare_item.rating_set.all().order_by('pk')
        for i, rating in enumerate(ratings):
            rating.question = i
            rating.save(update_fields=['question'])


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0015_ordering'),
    ]

    operations = [
        migrations.RunPython(update, reverse_code=migrations.RunPython.noop),
    ]
