# Generated by Django 2.1.7 on 2019-03-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0016_rating_question_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='creation_date',
            new_name='created',
        ),
    ]
