# Generated by Django 2.1.1 on 2018-09-24 07:35

from django.db import migrations


def update(apps, schema_editor):
    Study = apps.get_model('lrex_study', 'Study')
    Trial = apps.get_model('lrex_trial', 'Trial')
    for study  in Study.objects.filter(require_participant_id =False):
        for i, trial  in enumerate(Trial.objects.filter(questionnaire__study=study).order_by('created'), 1):
            trial.subject_id = i
            trial.save(update_fields=['subject_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0017_rename_created'),
    ]

    operations = [
        migrations.RunPython(update, reverse_code=migrations.RunPython.noop),
    ]
