# Generated by Django 2.1.7 on 2019-03-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0018_subject_id_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='subject_id',
            field=models.CharField(help_text='Provide an identification number/name (as instructed by the experimenter).', max_length=200, verbose_name='ID'),
        ),
    ]
