# Generated by Django 2.2 on 2019-04-17 15:33

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0019_subject_id_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireblock',
            name='instructions',
            field=markdownx.models.MarkdownxField(blank=True, help_text='These instructions will be presented to the participant before the experiment begins.', max_length=5000, null=True),
        ),
    ]
