# Generated by Django 2.2 on 2019-04-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0020_mardown'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
