# Generated by Django 2.2.1 on 2019-05-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0021_trial_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireblock',
            name='randomization',
            field=models.CharField(blank=True, choices=[('pseudo', 'Pseudo-randomize'), ('none', 'Keep item order'), ('true', 'Randomize')], default='pseudo', help_text='Randomize items in each questionnaire block', max_length=8),
        ),
    ]
