# Generated by Django 2.2.2 on 2019-07-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0023_questionnaireitem_question_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('scale_order', models.CharField(blank=True, max_length=200, null=True)),
                ('questionnaire_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrex_trial.QuestionnaireItem')),
            ],
        ),
    ]
