# Generated by Django 2.2.2 on 2019-07-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0023_questionnaireitem_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireblock',
            name='instructions',
            field=models.TextField(blank=True, help_text='These instructions will be presented to the participant before the questionnaire block begins.', max_length=2000, null=True),
        ),
    ]
