# Generated by Django 2.2.2 on 2019-07-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0024_questionproperty'),
        ('lrex_trial', '0024_auto_20190716_1045'),
    ]

    operations = [
    ]
