# Generated by Django 2.2.2 on 2019-07-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0025_merge_20190716_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionproperty',
            options={'ordering': ['number']},
        ),
    ]
