# Generated by Django 2.2.4 on 2019-08-28 14:22

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0026_auto_20190716_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireblock',
            name='instructions',
            field=markdownx.models.MarkdownxField(blank=True, help_text='These instructions will be presented to the participant before the questionnaire block begins.', max_length=2000, null=True),
        ),
    ]
