# Generated by Django 2.2.5 on 2019-09-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_trial', '0027_auto_20190828_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireblock',
            name='randomization',
            field=models.CharField(blank=True, choices=[('pseudo', 'Pseudo-randomize'), ('none', 'Keep item order'), ('true', 'Randomize')], default='pseudo', help_text='Randomize items in each questionnaire block.', max_length=8),
        ),
    ]
