# Generated by Django 2.2.5 on 2019-10-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0042_auto_20191009_0712'),
        ('lrex_trial', '0028_auto_20190930_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicsValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2000)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrex_study.DemographicField')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrex_trial.Trial')),
            ],
            options={
                'ordering': ['trial', 'field'],
            },
        ),
    ]
