# Generated by Django 2.2.5 on 2019-10-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0042_auto_20191009_0712'),
        ('lrex_trial', '0029_demographicsvalue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemographicsValue',
            new_name='DemographicValue',
        ),
    ]
