# Generated by Django 2.2.11 on 2020-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accept_emails',
            field=models.BooleanField(default=False, help_text='Allow L-Rex admin to send me emails about technical problems or other issues with my studies.'),
        ),
    ]
