# Generated by Django 2.2.14 on 2021-02-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accept_emails',
            field=models.BooleanField(default=False, help_text='Allow L-Rex admin to contact me via e-mail about important technical issues, e.g., server problems.'),
        ),
    ]
