# Generated by Django 2.0.1 on 2018-01-11 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lrex_trial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBinaryResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('yes', models.BooleanField()),
                ('user_trial_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrex_trial.UserTrialItem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
