# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lrex_trial', '0001_initial'),
        ('lrex_response', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbinaryresponse',
            name='user_trial_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrex_trial.UserTrialItem'),
        ),
    ]
