# Generated by Django 2.0.1 on 2018-03-22 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('item_type', models.CharField(choices=[('txt', 'Text')], default='txt', max_length=3)),
                ('rating_instructions', models.TextField(max_length=1024)),
                ('rating_question', models.CharField(blank=True, max_length=200, null=True)),
                ('rating_legend', models.TextField(blank=True, max_length=1024, null=True)),
                ('password', models.CharField(max_length=200)),
                ('allow_anonymous', models.BooleanField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scalevalue',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrex_study.Study'),
        ),
    ]
