# Generated by Django 2.1 on 2018-09-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(help_text='TODO This text will precede the stimulus (e.g. "How acceptable is this sentence?")', max_length=200),
        ),
    ]
