# Generated by Django 2.0.1 on 2018-05-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='item_type',
            field=models.CharField(choices=[('txt', 'Text'), ('aul', 'Audio Link')], default='txt', max_length=3),
        ),
    ]
