# Generated by Django 2.1.1 on 2018-09-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(help_text='Give your study a name.', max_length=200),
        ),
    ]
