# Generated by Django 2.1 on 2018-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='legend',
            field=models.CharField(blank=True, help_text='Legend to clarify the scale (e.g. "1 = bad, 5 = good")', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(help_text='Question text for this item (e.g. "How acceptable is this sentence?")', max_length=1000),
        ),
    ]
