# Generated by Django 2.0.1 on 2018-05-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0002_auto_20180514_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(help_text='TODO', max_length=200, unique=True),
        ),
    ]
