# Generated by Django 2.1 on 2018-09-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0002_auto_20180905_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='progress',
        ),
    ]
