# Generated by Django 2.0.1 on 2018-04-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0002_study_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='study',
            name='start_time',
        ),
        migrations.AddField(
            model_name='study',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='trial_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='progress',
            field=models.CharField(choices=[('00sc', 'Create a study'), ('01ss', 'Configure the rating scale '), ('02ec', 'Create a new experiment'), ('03ic', 'Create or upload experiment items'), ('04iv', 'Validate the experiment items consistancy'), ('05lc', 'Generate item lists'), ('06sq', 'Generate questionnaires'), ('07sp', 'Publish the study')], default='00sc', max_length=4),
        ),
    ]
