# Generated by Django 2.0.1 on 2018-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0002_auto_20180224_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='response_question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
