# Generated by Django 2.1.1 on 2018-09-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0002_title_not_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='shared_with',
            field=models.CharField(blank=True, help_text='Give other users access to the study, enter comma separated user names.', max_length=200, null=True),
        ),
    ]
