# Generated by Django 2.0.1 on 2018-03-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0003_auto_20180312_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='allow_anonymous',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='password',
            field=models.CharField(default='lrex', max_length=200),
            preserve_default=False,
        ),
    ]
