# Generated by Django 2.1 on 2018-09-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0003_remove_question_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='legend',
            field=models.CharField(blank=True, help_text='TODO This legend will appear below the stimulus to clarify the scale (e.g. "1 = bad, 5 = good").', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(help_text='TODO This text will precede the stimulus (e.g. "How acceptable is this sentence?")', max_length=1000),
        ),
    ]
