# Generated by Django 2.2.14 on 2021-01-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0003_auto_20201210_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='use_vertical_scale_layout',
            field=models.BooleanField(default=False, help_text='Enable if you want the response options to be presented below each other (default: horizontal layout). If multiple questions are defined, this setting applies to all of them.'),
        ),
    ]
