# Generated by Django 2.1.1 on 2018-09-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0003_study_shared_with'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['pk']},
        ),
    ]
