# Generated by Django 2.0.1 on 2018-04-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0003_auto_20180418_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(help_text='Title of the study', max_length=200),
        ),
    ]
