# Generated by Django 2.0.1 on 2018-05-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0003_auto_20180529_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalevalue',
            name='label',
            field=models.CharField(help_text='Provide a label for this point of the scale.', max_length=50),
        ),
        migrations.AlterField(
            model_name='study',
            name='allow_anonymous',
            field=models.BooleanField(help_text='Check this box if you want to allow participation without entering a name/ID.'),
        ),
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=models.DateField(blank=True, help_text='If you want to set a participation deadline, enter a date in the format YYYY-MM-DD.', null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Check this box to publish your study. It will then be available for participation.'),
        ),
        migrations.AlterField(
            model_name='study',
            name='password',
            field=models.CharField(help_text='This password will be required to participate in the study.', max_length=200),
        ),
        migrations.AlterField(
            model_name='study',
            name='rating_instructions',
            field=models.TextField(help_text='These instructions will be presented to the participant before the experiment begins.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='study',
            name='rating_legend',
            field=models.TextField(blank=True, help_text='This legend will appear below each stimulus to clarify the scale (e.g. "1 = bad, 5 = good").', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='rating_question',
            field=models.CharField(blank=True, help_text='This text will precede each stimulus (e.g. "How acceptable is this sentence?")', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(help_text='Give your study a name.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='trial_limit',
            field=models.IntegerField(blank=True, help_text='If you want to set a maximal number of participants, enter a number.', null=True, verbose_name='Maximal number of participants'),
        ),
    ]
