# Generated by Django 2.1.1 on 2018-10-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0004_sort_by_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='outro',
            field=models.TextField(blank=True, help_text='This text will be presented to the participant after the experiment is finished.', max_length=5000, null=True),
        ),
    ]
