# Generated by Django 2.2.7 on 2020-02-02 12:22

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0004_auto_20200110_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='short_instructions',
            field=markdownx.models.MarkdownxField(blank=True, help_text='The participant will be able to re-read this shorter version of the instructions duringparticipation.', max_length=3000, null=True),
        ),
    ]
