# Generated by Django 2.0.1 on 2018-03-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0004_auto_20180316_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
