# Generated by Django 2.0.1 on 2018-04-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0004_auto_20180418_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalevalue',
            name='label',
            field=models.CharField(help_text='TODO', max_length=50),
        ),
        migrations.AlterField(
            model_name='study',
            name='allow_anonymous',
            field=models.BooleanField(help_text='TODO'),
        ),
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=models.DateField(blank=True, help_text='TODO', null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='is_published',
            field=models.BooleanField(default=False, help_text='TODO'),
        ),
        migrations.AlterField(
            model_name='study',
            name='password',
            field=models.CharField(help_text='TODO', max_length=200),
        ),
        migrations.AlterField(
            model_name='study',
            name='rating_instructions',
            field=models.TextField(help_text='TODO', max_length=1024),
        ),
        migrations.AlterField(
            model_name='study',
            name='rating_legend',
            field=models.TextField(blank=True, help_text='TODO', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='rating_question',
            field=models.CharField(blank=True, help_text='TODO', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(help_text='TODO', max_length=200),
        ),
        migrations.AlterField(
            model_name='study',
            name='trial_limit',
            field=models.IntegerField(blank=True, help_text='TODO', null=True),
        ),
    ]
