# Generated by Django 2.0.5 on 2018-06-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0004_auto_20180530_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='item_type',
            field=models.CharField(choices=[('txt', 'Text'), ('aul', 'Audio Link')], default='txt', help_text='The items can be plain text or links to audio files (self-hosted).', max_length=3),
        ),
    ]
