# Generated by Django 2.2.14 on 2021-03-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0005_auto_20210212_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='answer_question_message',
        ),
    ]
