# Generated by Django 2.0.1 on 2018-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0005_auto_20180320_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
