# Generated by Django 2.0.1 on 2018-04-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0005_auto_20180418_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='progress',
            field=models.CharField(choices=[('00sc', 'Create a study'), ('01ss', 'Configure the rating scale'), ('02se', 'Create an experiment'), ('06sq', 'Generate questionnaires'), ('20sp', 'Publish the study')], default='00sc', max_length=4),
        ),
    ]
