# Generated by Django 2.2.7 on 2020-02-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0005_auto_20200219_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicfield',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='lrex_study.Study'),
        ),
        migrations.AlterField(
            model_name='question',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lrex_study.Study'),
        ),
        migrations.AlterField(
            model_name='scalevalue',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_values', to='lrex_study.Question'),
        ),
    ]
