# Generated by Django 2.0.5 on 2018-06-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0005_auto_20180602_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='progress',
            field=models.CharField(choices=[('00sc', 'Create a study'), ('01ss', 'Configure the rating scale'), ('02se', 'Create an experiment'), ('10ec', 'Complete the experiment creation'), ('11sq', 'Generate questionnaires'), ('20sp', 'Publish the study')], default='00sc', max_length=4),
        ),
    ]
