# Generated by Django 2.1.3 on 2018-11-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0005_study_outro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['-pk']},
        ),
    ]
