# Generated by Django 2.1.3 on 2018-11-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0006_reverse_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='generate_participation_code',
            field=models.BooleanField(default=False, help_text='Generate a proof code for the subject participation.'),
        ),
    ]
