# Generated by Django 2.0.5 on 2018-06-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0006_auto_20180604_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='allow_anonymous',
        ),
        migrations.AddField(
            model_name='study',
            name='require_participant_id',
            field=models.BooleanField(default=False, help_text='Enable if you want participants to enter some ID before participation.'),
        ),
        migrations.AlterField(
            model_name='study',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Enable to publish your study. It will then be available for participation.'),
        ),
    ]
