# Generated by Django 2.2.14 on 2021-03-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0006_remove_study_answer_question_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='field_required_message',
            field=models.CharField(default='This field is required.', help_text='Error message shown to participant if a required field was not submitted. Used for e.g. questions, comments, demographics.', max_length=500),
        ),
    ]
