# Generated by Django 2.2.7 on 2020-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0006_auto_20200226_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='participant_id',
            field=models.CharField(choices=[('none', 'No participant IDs'), ('enter', 'Participants are asked to enter an ID'), ('random', 'Generate random ID for each participant')], default='none', help_text='Choose the first option for fully anonymous participation. Choose the second option if you want to save an ID that participants receive independently (e.g., from an external participant recruitment platform). Choose the third option to generate a unique identifier (code) for each participant which will be displayed at the end of the questionnaire and which can be used e.g. as proof of participation.', max_length=8, verbose_name='participant ID'),
        ),
        migrations.AddField(
            model_name='study',
            name='participation_id_label',
            field=models.CharField(default='Participation ID', help_text='Label used for the participant ID form on the instruction page or for the participation code on the outro page, depending on the "participant ID" setting.', max_length=40),
        ),
        migrations.AddField(
            model_name='study',
            name='password_label',
            field=models.CharField(default='Password', help_text='Label used for the participant password form on the instruction page.', max_length=40),
        ),
    ]
