# Generated by Django 3.2.4 on 2021-07-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0007_study_field_required_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='has_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='study',
            name='participant_id',
            field=models.CharField(choices=[('none', 'No participant IDs'), ('enter', 'Participants have an external ID'), ('random', 'Generate random ID for each participant')], default='none', help_text='Choose the first option for fully anonymous participation. Choose the second option if you want to save an ID that participants receive independently (e.g., from an external participant recruitment platform). The ID is entered manually or passed via an URL parameter (see <a target="_blank" href="https://github.com/2e2a/l-rex/wiki">Wiki&#8599;</a> for details). Choose the third option to generate a unique identifier (code) for each participant which will be displayed at the end of the questionnaire and which can be used e.g. as proof of participation.', max_length=8, verbose_name='participant ID'),
        ),
    ]
