# Generated by Django 2.1.3 on 2018-11-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0007_study_generate_participation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='instructions',
            field=models.TextField(default='Please rate the following sentences on the scale.', help_text='These instructions will be presented to the participant before the experiment begins.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='study',
            name='outro',
            field=models.TextField(default='Thank you for participating!', help_text='This text will be presented to the participant after the experiment is finished.', max_length=5000),
        ),
    ]
