# Generated by Django 2.2.7 on 2020-02-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0007_auto_20200202_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='instructions_label',
            field=models.CharField(default='Show/hide short instructions', help_text='Label of the link to the short instructions that the participant can access during participation (if defined).', max_length=40),
        ),
    ]
