# Generated by Django 3.2.16 on 2023-01-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0008_auto_20210721_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='slug',
            field=models.SlugField(help_text='You can set a different title to be used in study URLs. This can for example be useful when the actual study name would give away crucial information to participants that they are not supposed to see.', max_length=110, unique=True, verbose_name='Title used in URLs'),
        ),
    ]
