# Generated by Django 2.1.5 on 2019-01-28 09:22

import apps.contrib.datefield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0008_default_instructions_and_outro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=apps.contrib.datefield.DateField(blank=True, help_text='Set a participation deadline.', null=True),
        ),
    ]
