# Generated by Django 2.2.7 on 2020-03-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0008_init_participation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='require_participant_id',
        ),
    ]
