# Generated by Django 2.2.11 on 2020-03-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0009_remove_study_require_participant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='consent_statement',
            field=models.CharField(default='I have read and understood the above information. I agree to participate in this study.', help_text='Participants will have to check a box with this statement before study begins.', max_length=500),
        ),
    ]
