# Generated by Django 2.1.5 on 2019-01-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0009_date_field_with_cal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='require_participant_id',
            field=models.BooleanField(default=False, help_text='Enable if you want participants to enter some ID before participation.', verbose_name='Participant ID required'),
        ),
    ]
