# Generated by Django 2.2.11 on 2020-03-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0010_study_consent_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='save_consent_form_label',
            field=models.CharField(default='Save this page', help_text='Label of the button used to save/print the consent form.', max_length=40),
        ),
    ]
