# Generated by Django 2.2.11 on 2020-03-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0011_study_save_consent_form_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='shared_with',
            new_name='shared_with_old',
        ),
    ]
