# Generated by Django 2.1.7 on 2019-03-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0011_instuctions_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='slug',
            field=models.SlugField(max_length=110, unique=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(help_text='Give your study a name.', max_length=100),
        ),
    ]
