# Generated by Django 2.2.11 on 2020-03-20 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lrex_study', '0012_auto_20200320_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Give other users access to the study.', related_name='shared_studies', to=settings.AUTH_USER_MODEL),
        ),
    ]
