# Generated by Django 2.1.7 on 2019-03-04 08:27

import apps.contrib.datefield
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0012_slug_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['study', 'number']},
        ),
        migrations.AlterModelOptions(
            name='scalevalue',
            options={'ordering': ['question', 'number']},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scalevalue',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='created_date',
            field=apps.contrib.datefield.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
