# Generated by Django 2.1.1 on 2018-09-24 07:35
from datetime import timedelta

from django.db import migrations
from django.utils.timezone import now


def update(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    for user in User.objects.all():
        studies = user.study_set.all().order_by('-pk')
        created_date = now()
        for study in studies:
            study.created_date = created_date
            created_date -= timedelta(days=1)
            study.save(update_fields=['created_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0013_ordering'),
    ]

    operations = [
        migrations.RunPython(update, reverse_code=migrations.RunPython.noop),
    ]
