# Generated by Django 2.2.11 on 2020-03-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0014_migrate_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='shared_with_old',
        ),
    ]
