# Generated by Django 2.1.1 on 2018-09-24 07:35
from datetime import timedelta

from django.db import migrations
from django.utils.timezone import now


def update(apps, schema_editor):
    Study = apps.get_model('lrex_study', 'Study')
    for study in Study.objects.all():
        questions = study.question_set.all().order_by('pk')
        for i, question in enumerate(questions):
            question.number = i
            question.save(update_fields=['number'])


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0014_study_created_date_update'),
    ]

    operations = [
        migrations.RunPython(update, reverse_code=migrations.RunPython.noop),
    ]
