# Generated by Django 2.2.11 on 2020-04-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0015_remove_study_shared_with_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='participation_id_label',
            field=models.CharField(default='Participation ID', help_text='Label used for the participant ID form on the instruction page or for the participation code on the outro page, depending on the "participant ID" setting.', max_length=40, verbose_name='Participation ID label'),
        ),
    ]
