# Generated by Django 2.1.7 on 2019-03-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0016_scale_value_number_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='progress',
            field=models.CharField(choices=[('00-std-crt', 'Create a study'), ('10-qst-crt', 'Create a question'), ('11-ins-edt', 'Edit the instructions'), ('20-exp-crt', 'Create an experiment'), ('29-exp-cmp', 'Complete the experiment creation'), ('30-std-qnr-gen', 'Generate questionnaires'), ('40-std-pub', 'Publish the study')], default='00-std-crt', max_length=16),
        ),
    ]
