# Generated by Django 2.1.7 on 2019-03-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0017_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='password',
            field=models.CharField(blank=True, help_text='This password will be required to participate in the study.', max_length=200, null=True),
        ),
    ]
