# Generated by Django 2.1.7 on 2019-04-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0018_password_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='progress',
        ),
    ]
