# Generated by Django 2.2.14 on 2020-08-28 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0019_auto_20200516_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=models.DateField(blank=True, help_text='Set a participation deadline.', null=True),
        ),
    ]
