# Generated by Django 2.1.7 on 2019-04-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0020_instructions_default_in_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='outro',
            field=models.TextField(blank=True, help_text='This text will be presented to the participant after the experiment is finished.', max_length=5000, null=True),
        ),
    ]
