# Generated by Django 2.2.14 on 2020-12-05 15:41

import apps.contrib.datefield
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0020_auto_20200828_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalevalue',
            name='label',
            field=models.CharField(help_text='Provide a label for this point of the scale.', max_length=1000),
        ),
    ]
