# Generated by Django 2.2.14 on 2020-12-10 10:32

import apps.contrib.datefield
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0021_auto_20201205_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalevalue',
            name='label',
            field=models.TextField(help_text='Provide a label for this point of the scale.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='study',
            name='created_date',
            field=apps.contrib.datefield.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=apps.contrib.datefield.DateField(blank=True, help_text='Set a participation deadline.', null=True),
        ),
    ]
