# Generated by Django 2.2 on 2019-04-17 15:33

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0021_outro_default_in_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='instructions',
            field=markdownx.models.MarkdownxField(blank=True, help_text='These instructions will be presented to the participant before the experiment begins.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='outro',
            field=markdownx.models.MarkdownxField(blank=True, help_text='This text will be presented to the participant after the experiment is finished.', max_length=5000, null=True),
        ),
    ]
