# Generated by Django 2.2 on 2019-04-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0022_mardown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='item_type',
            field=models.CharField(choices=[('txt', 'Plain text'), ('mkd', 'Rich text with markdown'), ('aul', 'Audio link')], default='txt', help_text='The items can be plain text or markdown rich text or links to audio files (self-hosted).', max_length=3),
        ),
    ]
