# Generated by Django 2.2 on 2019-04-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0023_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='continue_label',
            field=models.CharField(default='Continue', help_text='Label of the "Continue" button used during participation.', max_length=40),
        ),
    ]
