# Generated by Django 2.2 on 2019-04-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0024_study_continue_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='use_blocks',
            field=models.BooleanField(default=False, help_text='Enable if you want to divide the questionnaire into separate parts (blocks) with individual instructions'),
        ),
    ]
