# Generated by Django 2.1.1 on 2018-09-24 07:35
from datetime import timedelta

from django.db import migrations
from django.utils.timezone import now


def update(apps, schema_editor):

    def _has_blocks(study):
        blocks = set()
        for experiment in study.experiment_set.all():
            blocks.update(set([item.block for item in experiment.item_set.all()]))
        return len(blocks) > 1

    Study = apps.get_model('lrex_study', 'Study')
    for study in Study.objects.all():
        study.use_blocks = _has_blocks(study)
        study.save(update_fields=['use_blocks'])


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0025_study_use_blocks'),
    ]

    operations = [
        migrations.RunPython(update, reverse_code=migrations.RunPython.noop),
    ]
