# Generated by Django 2.2.2 on 2019-07-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0029_question_randomize_scale'),
        ('lrex_study', '0029_question_rating_comment'),
    ]

    operations = [
    ]
