# Generated by Django 2.2.4 on 2019-08-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0030_merge_20190716_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='enable_item_rating_feedback',
            field=models.BooleanField(default=False, help_text='Allows you to define feedback shown to participants for individual item ratings.'),
        ),
    ]
