# Generated by Django 2.2.4 on 2019-08-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0031_study_enable_item_rating_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='feedback_message',
            field=models.CharField(default='Please note the following feedback.', help_text='Message indicating that feedback is shown in for some ratings', max_length=500),
        ),
    ]
