# Generated by Django 2.2.4 on 2019-09-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0032_study_feedback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='item_type',
            field=models.CharField(choices=[('txt', 'Plain text'), ('mkd', 'Rich text with markdown'), ('aul', 'Audio links')], default='txt', help_text='The items can be plain text or markdown rich text or links to audio files (self-hosted).', max_length=3),
        ),
    ]
