# Generated by Django 2.2.5 on 2019-09-30 09:21

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0033_auto_20190904_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='contact_affiliation',
            field=models.CharField(blank=True, help_text='Your affiliation (e.g., university or research institute) shown to participants as part of the contact information.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='contact_details',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Additional details shown to participants as part of the contact information.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Your email shown to participants as part of the contact information.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Your name shown to participants as part of the contact information.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='privacy_statement',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Privacy statement shown to the participants. Should include who has access to the data, how long will it be stored, for what purpose, etc.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='legend',
            field=models.CharField(blank=True, help_text='Legend to clarify the scale (e.g. "1 = bad, 5 = good").', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(help_text='Question text for this item (e.g. "How acceptable is this sentence?").', max_length=1000),
        ),
        migrations.AlterField(
            model_name='study',
            name='feedback_message',
            field=models.CharField(default='Please note the following feedback.', help_text='Message indicating that feedback is shown for some ratings.', max_length=500),
        ),
        migrations.AlterField(
            model_name='study',
            name='generate_participation_code',
            field=models.BooleanField(default=False, help_text='Generate a proof code for participation.'),
        ),
        migrations.AlterField(
            model_name='study',
            name='pseudo_randomize_question_order',
            field=models.BooleanField(default=False, help_text='Show questions in random order, if multiple questions defined.'),
        ),
        migrations.AlterField(
            model_name='study',
            name='require_participant_id',
            field=models.BooleanField(default=False, help_text='Enable if you want participants to enter an ID before participation.', verbose_name='Participant ID required'),
        ),
        migrations.AlterField(
            model_name='study',
            name='shared_with',
            field=models.CharField(blank=True, help_text='Give other users access to the study. Enter comma-separated user names (e.g. "user1, user2").', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='use_blocks',
            field=models.BooleanField(default=False, help_text='Enable if you want to divide the questionnaire into separate parts (blocks) with individual instructions.'),
        ),
    ]
