# Generated by Django 2.2.5 on 2019-10-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0035_study_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='contact_label',
            field=models.CharField(default='Contact', help_text='Label for "Contact" used during participation.', max_length=40),
        ),
        migrations.AddField(
            model_name='study',
            name='privacy_statement_label',
            field=models.CharField(default='Privacy statement', help_text='Label for "Privacy statement" used during participation.', max_length=40),
        ),
    ]
