# Generated by Django 2.2.5 on 2019-10-01 11:35

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0036_auto_20191001_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='randomize_scale',
            field=models.BooleanField(default=False, help_text='Show scale labels in random order.'),
        ),
        migrations.AlterField(
            model_name='study',
            name='contact_affiliation',
            field=models.CharField(blank=True, help_text='Your affiliation (e.g., university or research institute) will be shown to participants as part of the contact information before the study begins.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='contact_details',
            field=markdownx.models.MarkdownxField(blank=True, help_text='You can optionally provide additional information about you and/or the research project (e.g., "This study is part of the research project XY, for more information, see ..."). This information will be shown to participants before the study begins.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='This e-mail address will be shown to participants as part of the contact information before the study begins.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='contact_name',
            field=models.CharField(blank=True, help_text='This name will be shown to participants as part of the contact information before the study begins.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='feedback_message',
            field=models.CharField(default='Please note the following feedback.', help_text='Message indicating that feedback is shown for some ratings (only if feedback feature is enabled).', max_length=500),
        ),
        migrations.AlterField(
            model_name='study',
            name='intro',
            field=markdownx.models.MarkdownxField(blank=True, help_text='This text will be presented to the participants on the first page.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='outro',
            field=markdownx.models.MarkdownxField(blank=True, help_text='This text will be presented to the participants on the last page.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='privacy_statement',
            field=markdownx.models.MarkdownxField(blank=True, help_text='This statement will be shown to the participants before the study begins. It should be stated whether the study is fully anonymous or not. If you ask for an individual ID or personal data in your study, the privacy statement should include the following information: for what purpose is the ID/personal data collected, how long will the data be stored in non-anonymized form, and who is responsible for data processing?', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='pseudo_randomize_question_order',
            field=models.BooleanField(default=False, help_text='Show questions in random order (if multiple questions are defined).'),
        ),
    ]
