# Generated by Django 2.2.5 on 2019-10-01 11:37

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0037_auto_20191001_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='contact_affiliation',
            field=models.CharField(blank=True, help_text='This affiliation (e.g., university or research institute) will be shown to participants as part of the contact information before the study begins.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='privacy_statement',
            field=markdownx.models.MarkdownxField(blank=True, help_text='This statement will be shown to the participants before the study begins. It should state whether the study is fully anonymous or not. If you ask for individual IDs or personal data in your study, the privacy statement should include the following information: for what purpose is the ID/personal data collected, how long will the data be stored in non-anonymized form, and who is responsible for data processing?', max_length=5000, null=True),
        ),
    ]
