# Generated by Django 2.2.5 on 2019-10-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0038_auto_20191001_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='instructions_label',
            field=models.CharField(default='Instructions', help_text='Label of the "Instructions" link used during participation.', max_length=40),
        ),
        migrations.AddField(
            model_name='study',
            name='link_instructions',
            field=models.BooleanField(default=False, help_text='Make a link to the instructions available at any time during participation.'),
        ),
    ]
