# Generated by Django 2.2.5 on 2019-10-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0039_auto_20191001_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='link_block_instructions',
            field=models.BooleanField(default=False, help_text='Make the current block instructions available under the instructions link.'),
        ),
    ]
