# Generated by Django 2.2.5 on 2019-10-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0040_study_link_block_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of a demographic field.', max_length=500)),
                ('number', models.IntegerField(default=0)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrex_study.Study')),
            ],
            options={
                'ordering': ['study', 'number'],
            },
        ),
    ]
