# Generated by Django 2.2.5 on 2019-10-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0041_demographicfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demographicfield',
            options={'ordering': ['study', 'pk']},
        ),
        migrations.RemoveField(
            model_name='demographicfield',
            name='number',
        ),
    ]
