# Generated by Django 2.2.5 on 2019-10-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0042_auto_20191009_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicfield',
            name='name',
            field=models.CharField(help_text='You can enter a demographic question (e.g., "age" or "native languages"). The participants will have to answer it (free text input) at the beginning of the study.', max_length=500, verbose_name='question'),
        ),
    ]
