# Generated by Django 2.2.5 on 2019-10-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0043_auto_20191009_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='comment_label',
            field=models.CharField(default='Comment', help_text='Label used for the comment field.', max_length=40),
        ),
        migrations.AddField(
            model_name='study',
            name='optional_label',
            field=models.CharField(default='optional', help_text='Label used for user input fields that can be optional, e.g. comment.', max_length=40),
        ),
    ]
