# Generated by Django 2.2.5 on 2019-10-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0044_auto_20191023_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='answer_question_message',
            field=models.CharField(default='Please answer this question.', help_text='Error message shown to participant, if the question was not answered.', max_length=500),
        ),
        migrations.AddField(
            model_name='study',
            name='answer_questions_message',
            field=models.CharField(default='Please answer all questions.', help_text='Error message shown to participant, if a question was not answered.', max_length=500),
        ),
    ]
