# Generated by Django 2.2.5 on 2019-10-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0045_auto_20191023_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='generate_participation_code',
        ),
    ]
