# Generated by Django 2.2.14 on 2020-10-28 07:23

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=210, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('text', markdownx.models.MarkdownxField(max_length=5000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-date'],
            },
        ),
    ]
