# Generated by Django 2.0.1 on 2018-03-22 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lrex_experiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('condition', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['number', 'condition'],
            },
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrex_experiment.Experiment')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lrex_item.Item')),
                ('text', models.TextField(max_length=1024)),
            ],
            bases=('lrex_item.item',),
        ),
        migrations.AddField(
            model_name='itemlist',
            name='items',
            field=models.ManyToManyField(to='lrex_item.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrex_experiment.Experiment'),
        ),
    ]
