# Generated by Django 2.0.1 on 2018-03-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(to='lrex_item.Item'),
        ),
    ]
