# Generated by Django 2.0.1 on 2018-04-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(help_text='TODO', max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='number',
            field=models.IntegerField(help_text='TODO'),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='text',
            field=models.TextField(help_text='TODO', max_length=1024),
        ),
    ]
