# Generated by Django 2.1 on 2018-09-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquestion',
            name='legend',
            field=models.CharField(blank=True, help_text='Legend to clarify the scale (e.g. "1 = bad, 5 = good")', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='itemquestion',
            name='question',
            field=models.CharField(help_text='Question text (e.g. "How acceptable is this sentence?")', max_length=1000),
        ),
        migrations.AlterField(
            model_name='itemquestion',
            name='scale_labels',
            field=models.CharField(blank=True, help_text='Labels for the rating scale, separated by commas (e.g. "1,2,3,4,5")', max_length=500, null=True),
        ),
    ]
