# Generated by Django 2.2.7 on 2020-01-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0002_auto_20191218_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfeedback',
            name='scale_values',
            field=models.CharField(help_text='Scale values, separated by commas (e.g. "1,3"). If a label contains a comma itself, escape it with "\\" (e.g. "A,B,Can\'t decide\\, I like both"). The feedback will be shown to the participant if one of these ratings is selected.', max_length=500),
        ),
        migrations.AlterField(
            model_name='itemquestion',
            name='scale_labels',
            field=models.CharField(blank=True, help_text='Individual rating scale labels for this item, separated by commas (e.g. "1,2,3,4,5"). If a label contains a comma itself, escape it with "\\" (e.g. "A,B,Can\'t decide\\, I like both"). Note that this will only overwrite the displayed labels, but the responses will be saved according to the general scale specified in the study settings.', max_length=500, null=True),
        ),
    ]
