# Generated by Django 2.1.1 on 2018-09-24 07:35
from django.db import migrations, models

from apps.contrib.utils import slugify_unique


def gen_slug(apps, schema_editor):
    Item = apps.get_model('lrex_item', 'Item')
    for item in Item.objects.all():
        slug = '{}--{}{}'.format(item.experiment.slug, item.number, item.condition)
        item.slug = slugify_unique(slug, Item)
        item.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0002_item_slug_1'),
    ]

    operations = [
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop),
    ]
