# Generated by Django 2.1 on 2018-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0002_auto_20180908_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquestion',
            name='legend',
            field=models.CharField(blank=True, help_text='Individual legend for this item to clarify the scale (e.g. "1 = bad, 5 = good")', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='itemquestion',
            name='question',
            field=models.CharField(help_text='Individual question text for this item (e.g. "How acceptable is this sentence?")', max_length=1000),
        ),
        migrations.AlterField(
            model_name='itemquestion',
            name='scale_labels',
            field=models.CharField(blank=True, help_text='Individual rating scale labels for this item, separated by commas (e.g. "1,2,3,4,5"). Note that this will only overwrite the displayed labels, but the responses will be saved according to the general scale specified in the study settings.', max_length=500, null=True),
        ),
    ]
