# Generated by Django 2.0.1 on 2018-05-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0002_audiolinkitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(help_text='Condition of the item (character limit: 8)', max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='number',
            field=models.IntegerField(help_text='Number of the item'),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='text',
            field=models.TextField(help_text='Content of the item (character limit: 1024).', max_length=1024),
        ),
    ]
