# Generated by Django 2.2.7 on 2020-02-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0003_auto_20200110_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lrex_materials.Materials'),
        ),
        migrations.AlterField(
            model_name='itemfeedback',
            name='item',
            field=models.ForeignKey(help_text='Item for the feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='item_feedback', to='lrex_item.Item'),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='lrex_materials.Materials'),
        ),
        migrations.AlterField(
            model_name='itemquestion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_questions', to='lrex_item.Item'),
        ),
    ]
