# Generated by Django 2.0.5 on 2018-06-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0003_auto_20180530_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolinkitem',
            name='url',
            field=models.URLField(help_text='Link to the audio file (e.g., https://yourserver.org/item1a.ogg).', verbose_name='URL'),
        ),
    ]
