# Generated by Django 2.1.4 on 2018-12-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0004_item_slug_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='block',
            field=models.IntegerField(default=1, help_text='Number of the questionnaire block in which the item will appear'),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='text',
            field=models.TextField(help_text='Content of the item (character limit: 1024)', max_length=1024),
        ),
    ]
