# Generated by Django 2.1.4 on 2019-01-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0005_item_help'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemquestion',
            options={'ordering': ['question', 'pk']},
        ),
    ]
