# Generated by Django 2.1.7 on 2019-03-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0007_slug_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['experiment', 'block', 'number', 'condition']},
        ),
        migrations.AlterModelOptions(
            name='itemlist',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='itemquestion',
            options={'ordering': ['item', 'number']},
        ),
        migrations.AddField(
            model_name='itemlist',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemquestion',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
