# Generated by Django 2.1.1 on 2018-09-24 07:35
from datetime import timedelta

from django.db import migrations
from django.utils.timezone import now


def update(apps, schema_editor):
    Materials = apps.get_model('lrex_materials', 'Materials')
    for materials in Materials.objects.all():
        item_lists = materials.itemlist_set.all().order_by('pk')
        for i, item_list in enumerate(item_lists):
            item_list.number = i
            item_list.save(update_fields=['number'])


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0008_ordering'),
    ]

    operations = [
        migrations.RunPython(update, reverse_code=migrations.RunPython.noop),
    ]
