# Generated by Django 2.1.7 on 2019-03-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0009_itemlist_number_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemlist',
            options={'ordering': ['experiment', 'number']},
        ),
    ]
