# Generated by Django 2.1.1 on 2018-09-24 07:35
from datetime import timedelta

from django.db import migrations
from django.utils.timezone import now


def update(apps, schema_editor):
    Item = apps.get_model('lrex_item', 'Item')
    for item in Item.objects.all():
        item_questions = item.itemquestion_set.all().order_by('pk')
        for i, item_question in enumerate(item_questions):
            item_question.number = i
            item_question.save(update_fields=['number'])


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0010_ordering'),
    ]

    operations = [
        migrations.RunPython(update, reverse_code=migrations.RunPython.noop),
    ]
