# Generated by Django 2.1.7 on 2019-03-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0011_itemquestion_number_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['block', 'number', 'condition']},
        ),
    ]
