# Generated by Django 2.2 on 2019-04-18 12:19

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0013_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lrex_item.Item')),
                ('text', markdownx.models.MarkdownxField(help_text='Content of the item with markdown formatting (character limit: 1024)', max_length=1024)),
            ],
            bases=('lrex_item.item',),
        ),
    ]
