# Generated by Django 2.2.4 on 2019-08-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_study', '0031_study_enable_item_rating_feedback'),
        ('lrex_item', '0014_markdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_values', models.CharField(help_text='Scale values, separated by commas (e.g. "1,3"). The feedback will be shown to the participant if one of these ratings is selected.', max_length=500)),
                ('feedback', models.TextField(help_text='Feedback shown to the participant for the selected rating scale values.', max_length=5000)),
                ('item', models.ForeignKey(help_text='Item for the feedback.', on_delete=django.db.models.deletion.CASCADE, to='lrex_item.Item')),
                ('question', models.ForeignKey(help_text='Question for the feedback.', on_delete=django.db.models.deletion.CASCADE, to='lrex_study.Question')),
            ],
            options={
                'ordering': ['item', 'question'],
            },
        ),
    ]
