# Generated by Django 2.2.4 on 2019-08-22 10:10

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0015_itemfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolinkitem',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Additional description shown with the audio item.', max_length=5000, null=True),
        ),
    ]
