# Generated by Django 2.1.1 on 2018-09-24 07:35
from django.db import migrations, models

from apps.contrib.utils import slugify_unique


def copy_urls(apps, schema_editor):
    AudioLinkItem = apps.get_model('lrex_item', 'AudioLinkItem')
    for item in AudioLinkItem.objects.all():
        item.urls = str(item.url)
        item.save(update_fields=['urls'])


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0017_audiolinkitem_urls'),
    ]

    operations = [
        migrations.RunPython(copy_urls, reverse_code=migrations.RunPython.noop),
    ]
