# Generated by Django 2.2.4 on 2019-08-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0019_auto_20190822_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolinkitem',
            name='urls',
            field=models.TextField(help_text='Links to the audio files separated by commas (e.g., https://yourserver.org/item1a-i.ogg,https://yourserver.org/item1a-ii.ogg). ', max_length=5000, verbose_name='URLs'),
        ),
    ]
