# Generated by Django 2.2.4 on 2019-09-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0020_auto_20190823_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemfeedback',
            options={'ordering': ['item', 'question', 'pk']},
        ),
    ]
