# Generated by Django 2.2.5 on 2019-09-30 08:50

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lrex_item', '0021_auto_20190904_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolinkitem',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Additional description presented with the audio item.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='block',
            field=models.IntegerField(default=1, help_text='Number of the questionnaire block in which the item will appear.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(help_text='Condition of the item (character limit: 8).', max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='number',
            field=models.IntegerField(help_text='Number of the item.'),
        ),
        migrations.AlterField(
            model_name='itemquestion',
            name='question',
            field=models.CharField(help_text='Individual question text for this item (e.g. "How acceptable is this sentence?").', max_length=1000),
        ),
        migrations.AlterField(
            model_name='markdownitem',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='Content of the item with markdown formatting (character limit: 1024).', max_length=1024),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='text',
            field=models.TextField(help_text='Content of the item (character limit: 1024).', max_length=1024),
        ),
    ]
